### ISSUE TITLE
Can I use the current version ?

### ISSUE THREAD

**Issue by rednaks** [rednaks/caniusepython3#1]
The original `caniusepython3` project checks if the latest version of the dependency supports python3. this can be problematic for two reasons:
### It's misleading:
`ciup3` will tell me that a package X is compatible with python3 but since I have an older version installed I will not try to investigate and  after switching to python3 my project will broke.

### It's all about minimizing upgrade costs:
Since upgrading costs too much, we use tools to minimize this cost, as of security vulnerabilities, we use vulnerability assessment tools to decide weather we are impacted or not. to avoid upgrading.

### Tasks:
- [x] refactor datastructure
- [x] requirements
- [x] metadata
- [x] projects
- [x]  Option in the CLI to choose to test the current installed version.
- [x]  Check PyPi with the specified version.
- [x]  TBD Disable overrides ?
